apiVersion: v1
kind: Service
metadata:
  name: {{ include "teams-frontend.fullname" . }}
  labels:
    {{- include "teams-frontend.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - port: 8080
      protocol: TCP
      name: http
  selector:
    {{- include "teams-frontend.selectorLabels" . | nindent 4 }}
